name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  # Show the full year's activity

          plugin_notable: yes
          plugin_notable_repositories: yes  # Show notable repositories
          plugin_notable_from: all  # Fetch from all public & private repositories
          plugin_notable_indepth: yes

          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size, lines  # Show extra details
          plugin_languages_sections: most-used  # Ensure it shows the most used languages
          plugin_languages_limit: 8  # Show up to 8 languages
          plugin_languages_threshold: 0%  # Avoid filtering out any languages
          plugin_languages_analysis_timeout: 60
