name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: OkoliEvans  # Replace with your GitHub username
          template: classic
          base: ""
          plugin_isocalendar: true
          plugin_languages: true
          plugin_habits: true
          plugin_followers: true
          plugin_stars: true
          plugin_traffic: true

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update metrics"
          git push
