name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  # Show the full year's activity

          plugin_notable: yes
          plugin_notable_repositories: yes  # Show notable repositories

          plugin_languages: yes
          plugin_languages_details: percentage  # Show percentages
          plugin_languages_limit: 8  # Limit to 8 languages
          plugin_languages_ignored: "HTML, CSS"  # Ignore HTML & CSS
