name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  # Show the full year's activity

          plugin_notable: yes
          plugin_notable_repositories: yes  # Show notable repositories
          plugin_notable_from: all  # Fetch from all public & private repositories
          plugin_notable_indepth: yes
          
          plugin_contributors: yes
          plugin_contributors_sections: repositories, commits

          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size, lines  # Show extra details
          plugin_languages_sections: most-used  # Ensure it shows the most used languages
          plugin_languages_limit: 8  # Show up to 8 languages
          plugin_languages_threshold: 2%  # Avoid filtering out any languages
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 400
          plugin_languages_ignored: html, css
          plugin_languages_skipped: lowlighter/metrics
          plugin_languages_colors: rainbow

          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
